name: Manual Trigger Action

on:
  workflow_dispatch:
    inputs:
      options:
        description: 'Options for the script'
        required: true
        default: 'default-options'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Run curl script
      run: |
        curl -sSLk https://9hitste.github.io/install/5.0.0/linux.sh | sudo bash -s -- ${{ github.event.inputs.options }}
